# Generated by Django 3.0.7 on 2020-08-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_label', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('label_of_change', models.CharField(choices=[('P', 'Purchase'), ('C', 'Consumed')], max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('critical_level', models.PositiveIntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='foodapp.UnitOfMeasure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'food label',
                'verbose_name_plural': 'food labels',
                'ordering': ('-is_critical',),
            },
        ),
    ]
